### PR TITLE
upgrade postgres version to 13.4

### PR DESCRIPTION
**Pull request by rsata**
Use more up to date version of postgres (13.4)

### CODE REVIEW

**Review by avimoondra — COMMENTED** [review]
seems fine to me, we run 13.4 in Cloud

There may be other places where we need to update this value?

e.g.

https://github.com/tryretool/retool-onpremise/blob/master/kubernetes/retool-postgres.yaml#L55

https://github.com/tryretool/retool-onpremise/blob/781b2c49e8ed6318173e34cd620088e21cfdf99c/docker-compose.yml#L94

maybe more: https://github.com/tryretool/retool-onpremise/search?q=postgres

tho updating the docker-compose, if someone repulls the repo for some reason - there will be a migration issue from 11 to 13. Will require a dump and restore. or pg_upgrade command

https://www.postgresql.org/docs/10/pgupgrade.html

image

**Review by kyle-retool — CHANGES_REQUESTED** [review]
@rsata What happens if someone pulls these updated configurations and creates a new Fargate deployment? We need to make sure their existing database doesn't get upgraded automatically (or that a new database isn't created).

**Comment by rsata** [comment]
not sure - was there anything else we changed when we last updated this? https://github.com/tryretool/retool-onpremise/pull/71

**Comment by avimoondra** [comment]
>We need to make sure their existing database doesn't get upgraded automatically

I don't think this happens (customers don't reference our template directly i beleive) last we checked / and tested this - just missing some references is only "blocker" @rsata @kyle-retool

**Pull request closed without merging**
